- name: Préparation
  hosts: all
  become: yes
  roles:
    #- preparation
- name: Configurer le server web
  hosts: web
  become: yes
  roles:
    #- install_apache2
    #- install_php
- name: Clone repo moodle
  hosts: web
  vars_files: group_vars/moodle.yml
  become: yes
  roles:
    #- clone_moodle
- name: Déployer MySQL et configurer
  hosts: db
  become: yes
  vars_files: 
    - vault.yml
  roles:
    - install_config_mysql

