- name: Préparation
  hosts: all
  become: yes
  roles:
    - preparation
- name: Configurer le server web
  hosts: web
  become: yes
  roles:
    - install_apache2
    - install_php
- name: Clone repo moodle
  hosts: web
  vars_files: group_vars/moodle.yml
  become: yes
  roles:
    - clone_moodle
- import_playbook: playbooks/install_mysql.yml
- name: Last config
  hosts: web
  become: yes
  vars_files: 
    - vault.yml
  roles:
    - last_config

