- name: Copy Apache2 configuration file
  copy:
    src: templates/apache2.conf
    dest: "/etc/apache2/apache2.conf"
  notify:
    - restart_apache2

- name: Copy index.html file
  copy:
    src: files/index.html
    dest: "/var/www/html"
  notify:
    - restart_apache2
