- name: Clone Moodle repository with specific branch
  git:
    repo: "{{ moodle_repo_url }}"
    dest: "{{ moodle_dest }}"
    version: "{{ moodle_branch }}"
    force: yes
  when: not moodle_dir.stat.exists
  notify:
    - restart_apache2
