---
- name: Setup MySQL database for Moodle using geerlingguy.mysql
  hosts: db
  become: true

  vars:
    mysql_root_password: "StrongRootPass123!"   # Customize strong root password
    moodle_db: "moodle"
    moodle_user: "moodle_user"
    moodle_password: "StrongMoodlePass456!"     # Customize strong moodle user password

  roles:
    - role: geerlingguy.mysql
      mysql_root_password: "{{ mysql_root_password }}"
      mysql_remove_anonymous_users: true
      mysql_disable_root_login_remotely: true
      mysql_remove_test_database: true
      mysql_databases:
        - name: "{{ moodle_db }}"
          encoding: utf8mb4
          collation: utf8mb4_unicode_ci
      mysql_users:
        - name: "{{ moodle_user }}"
          host: "%"
          password: "{{ moodle_password }}"
          priv: "{{ moodle_db }}.*:ALL"
          state: present

  tasks:
    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: true
